# fly.toml app configuration file generated for backend-small-field-7306 on 2025-08-25T22:10:13+04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'backend-small-field-7306'
primary_region = "iad"

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
